### ISSUE TITLE
content of pre-commig-config

### ISSUE THREAD

**Issue by bellerophons-pegasus** [bellerophons-pegasus/ssciwr_sdc_team14#2]
```
repos:
  - repo: 'https://github.com/kynan/nbstripout'
    rev: master
    hooks:
      - id: nbstripout
```
